title: Infoteket Stockholm AB
email: info@infoteket.nu
description: >-
  Infoteket Stockholm AB
baseurl: ""
url: "https://infoteket.nu"
theme: null

# Build settings
markdown: kramdown

# Exclude unnecessary files from the build
exclude:
  - README.md
  - .github/
